import { CollectionItem, ServiceItem, ProductItem, ProjectItem, TestimonialItem } from './types';

// Bespoke generated assets
export const HERO_IMAGE = '/src/assets/images/hero_living_room_1789814762457.jpg';
export const EDITORIAL_BEDROOM_IMAGE = '/src/assets/images/editorial_bedroom_1789814779286.jpg';
export const SCULPTURAL_CHAIR_IMAGE = '/src/assets/images/sculptural_chair_1789814793058.jpg';

export const BRAND = {
  export const BRAND = {
  name: 'CasaVera Interiors',
  shortName: 'CasaVera',
  tagline: 'Spaces Designed to Feel Like Home.',
  subheading: 'Thoughtfully curated interiors, timeless furniture, and refined details',
  address: 'Lahore, Punjab, Pakistan',
  email: 'Sumraumairsumraumair@gmail.com',
  phone: '+92 341 8054556',
  hours: 'Monday - Saturday: 10:00 AM - 8:00 PM PKT',
  weekendHours: 'Sunday: By Appointment Only',
  license: 'WhatsApp: 0341-8054556',};
export const TRUST_HIGHLIGHTS = [
  {
    title: 'Thoughtful Design',
    description: 'Every line, proportion, and texture serves both functional comfort and architectural balance.',
  },
  {
    title: 'Premium Materials',
    description: 'Responsibly sourced European white oak, natural travertine, unbleached linen, and hand-cast bronze.',
  },
  {
    title: 'Personalized Spaces',
    description: 'Custom bespoke layouts tailored precisely to your daily habits, lighting orientation, and lifestyle.',
  },
];

export const COLLECTIONS: CollectionItem[] = [
  {
    id: 'living',
    title: 'Living Spaces',
    subtitle: 'Warm Gatherings',
    description: 'Curated modular sofas, sculptural coffee tables, and architectural seating built for effortless ease.',
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
    itemCount: 24,
    featuredHighlight: 'Low-profile bouclé seating & brushed oak consoles',
    slug: 'living-spaces',
  },
  {
    id: 'bedrooms',
    title: 'Bedrooms',
    subtitle: 'Serene Sanctuaries',
    description: 'Low platform beds, breathable flax linens, and warm ambient illumination designed for deep rest.',
    image: EDITORIAL_BEDROOM_IMAGE,
    itemCount: 18,
    featuredHighlight: 'Solid oak headboards & organic woven textiles',
    slug: 'bedrooms',
  },
  {
    id: 'home-office',
    title: 'Home Office',
    subtitle: 'Quiet Focus',
    description: 'Refined executive desks, tactile leather blotters, and integrated wire management for clean contemplation.',
    image: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&w=1200&q=80',
    itemCount: 14,
    featuredHighlight: 'Ergonomic walnut desks & sculptural task lighting',
    slug: 'home-office',
  },
  {
    id: 'decor',
    title: 'Decor & Accessories',
    subtitle: 'Artisanal Accents',
    description: 'Hand-thrown stoneware vessels, sculptural catchalls, and fine art monographs that complete the room.',
    image: 'https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=1200&q=80',
    itemCount: 36,
    featuredHighlight: 'Hand-poured ceramics & volcanic stone artifacts',
    slug: 'decor-accessories',
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'interior-design',
    title: 'Interior Design',
    tagline: 'Full-Scope Concept to Realization',
    description: 'Personalized interior concepts designed around your lifestyle, architectural envelope, and aesthetic vision.',
    deliverables: [
      'Comprehensive 3D spatial renders & material mood boards',
      'Custom bespoke cabinetry & millwork design',
      'Architectural lighting plan & finish scheduling',
      'Full contractor liaison & site installation management',
    ],
    timeline: '8 – 16 Weeks',
    iconName: 'Sparkles',
  },
  {
    id: 'space-planning',
    title: 'Space Planning',
    tagline: 'Functional Optimization & Flow',
    description: 'Smart layouts that make every square meter work beautifully, ensuring fluid movement and natural light paths.',
    deliverables: [
      'Detailed scale 2D floor plans & circulation blueprints',
      'Ergonomic zoning for work, dining, and relaxation',
      'Sightline optimization & structural partition guidance',
      'Furniture placement & dimension allowance guides',
    ],
    timeline: '3 – 5 Weeks',
    iconName: 'LayoutGrid',
  },
  {
    id: 'styling-finishing',
    title: 'Styling & Finishing',
    tagline: 'Art, Objects & Tactile Layers',
    description: 'Furniture curation, ambient lighting, handwoven textures, gallery artwork, and delicate finishing details.',
    deliverables: [
      'White-glove curation of designer furniture & vintage finds',
      'Window drapery, custom rugs & textile palette selection',
      'Original art advisory & gallery framing consultation',
      'Final turnkey styling day with styling director',
    ],
    timeline: '4 – 6 Weeks',
    iconName: 'Compass',
  },
];

export const PRODUCTS: ProductItem[] = [
  {
    id: 'sculptural-lounge-chair',
    name: 'Sculptural Lounge Chair',
    category: 'Seating & Lounge',
    description: 'Sculpted cloud-soft bouclé upholstery framed by hand-finished European white oak with ergonomic low-slung proportions.',
    fullDetails: 'Designed in our Soho studio and crafted by master artisans in northern Italy. The chair combines high-resiliency dual-density foam with natural down-blend padding and a solid kiln-dried oak frame.',
    dimensions: '34" W × 36" D × 29" H (Seat Height: 16")',
    materials: 'Heavyweight Italian Bouclé, Solid White Oak, Natural Down Blend',
    origin: 'Crafted in Verona, Italy',
    leadTime: 'In Stock • Ready to ship in 3–5 business days',
    price: 1850,
    formattedPrice: '$1,850',
    image: SCULPTURAL_CHAIR_IMAGE,
    tag: 'Signature Piece',
    inStock: true,
    finishes: [
      { name: 'Oatmeal Bouclé', hex: '#EDE8DF' },
      { name: 'Earthy Charcoal', hex: '#2C2B29' },
      { name: 'Warm Terracotta', hex: '#C96F37' },
    ],
  },
  {
    id: 'handcrafted-ceramic-set',
    name: 'Handcrafted Ceramic Set',
    category: 'Artisanal Decor',
    description: 'A trio of wheel-thrown sculptural vessels crafted from raw coarse stoneware with a tactile unglazed exterior.',
    fullDetails: 'Each piece in this three-part vessel collection carries subtle organic marks from the potter wheel. Watertight interior glaze permits fresh botanical stems, while the rough exterior texture catches natural daylight.',
    dimensions: 'Large: 14" H × 8" D • Medium: 10" H × 6" D • Bowl: 5" H × 9" D',
    materials: 'High-fire Stoneware Clay, Matte Raw Mineral Finish',
    origin: 'Handmade in Kyoto, Japan',
    leadTime: 'In Stock • Ready to ship in 2–3 business days',
    price: 420,
    formattedPrice: '$420',
    image: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=1000&q=80',
    tag: 'Artisan Studio',
    inStock: true,
    finishes: [
      { name: 'Raw Sand', hex: '#D8CEBE' },
      { name: 'Smoked Basalt', hex: '#4A4845' },
    ],
  },
  {
    id: 'minimal-table-lamp',
    name: 'Minimal Table Lamp',
    category: 'Architectural Lighting',
    description: 'Solid Roman travertine pedestal paired with spun antiqued brass dome shade emitting a warm 2700K ambient glow.',
    fullDetails: 'An exploration of weight and light. The cylindrical base is quarried from natural unhoned Italian travertine stone, with distinctive natural porous veining. Fitted with a rotary solid brass dimmer dial.',
    dimensions: '12" Diameter Dome × 17.5" H (Base: 4.5" Diameter)',
    materials: 'Solid Italian Travertine, Spun Brass, Twisted Braided Fabric Cord',
    origin: 'Assembled in New York, NY',
    leadTime: 'In Stock • Ready to ship in 2–4 business days',
    price: 680,
    formattedPrice: '$680',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1000&q=80',
    tag: 'Bestseller',
    inStock: true,
    finishes: [
      { name: 'Brushed Brass & Travertine', hex: '#D4AF37' },
      { name: 'Blackened Bronze & Stone', hex: '#3A3835' },
    ],
  },
];

export const PROCESS_STEPS = [
  {
    number: '01',
    title: 'Discover',
    tagline: 'In-Depth Consultation',
    description: 'We listen to your daily rituals, aesthetic affinities, and spatial dilemmas to define your genuine lifestyle brief.',
    highlight: 'Site walkthrough & spatial audit',
  },
  {
    number: '02',
    title: 'Concept',
    tagline: 'Tailored Vision',
    description: 'We present bespoke spatial layouts, tactile mood palettes, custom furniture drawings, and photorealistic 3D perspectives.',
    highlight: 'Comprehensive material trays & samples',
  },
  {
    number: '03',
    title: 'Refine',
    tagline: 'Artisan Selection',
    description: 'Every textile, joinery junction, stone slab, and lighting fixture is vetted for longevity, comfort, and architectural cohesion.',
    highlight: 'Fixed procurement schedule & trade pricing',
  },
  {
    number: '04',
    title: 'Transform',
    tagline: 'Flawless Installation',
    description: 'Our white-glove team supervises general contractors, millworkers, and final turnkey styling down to the last art piece.',
    highlight: 'Move-in ready turnkey handover',
  },
];

export const PROJECTS: ProjectItem[] = [
  {
    id: 'tribeca-loft',
    title: 'The Tribeca Cast-Iron Loft',
    category: 'Living Room',
    location: 'Tribeca, New York',
    year: '2025',
    area: '3,800 sq ft',
    tagline: 'Expansive historic volume balanced with intimate warm minimalist zones.',
    description: 'A complete interior reinvention of a 19th-century cast-iron loft. Original Corinthian timber columns and 13-foot ceilings were highlighted with bespoke floating walnut joinery, travertine coffee tables, and customized low-slung linen seating.',
    heroImage: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    ],
    materialsUsed: ['Quarter-sawn White Oak', 'Roman Travertine', 'Unbleached Belgian Linen', 'Patinated Bronze'],
    palette: ['#F7F5F0', '#EDE8DF', '#C96F37', '#20242A'],
    clientVision: 'Create a sanctuary for quiet family mornings and gallery-calibre evening hosting in downtown Manhattan.',
  },
  {
    id: 'kyoto-residence',
    title: 'Kyoto Courtyard Sanctuary',
    category: 'Bedroom',
    location: 'Kyoto, Japan',
    year: '2025',
    area: '2,400 sq ft',
    tagline: 'Subdued Japanese aesthetics meeting tactile Scandinavian warmth.',
    description: 'Designed around an interior moss courtyard, this private master suite incorporates Japanese cedar slat screens, woven tatami grass borders, and a custom floating ash platform bed with concealed soft floor wash lighting.',
    heroImage: EDITORIAL_BEDROOM_IMAGE,
    gallery: [
      EDITORIAL_BEDROOM_IMAGE,
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80',
    ],
    materialsUsed: ['Hinoki Cypress', 'Handmade Washi Paper', 'Woven Natural Flax', 'Matte Clay Plaster'],
    palette: ['#F5EFEB', '#E3D7C7', '#736B5E', '#2B2622'],
    clientVision: 'An unhurried retreat prioritizing morning light meditation and acoustic stillness.',
  },
  {
    id: 'sonoma-oak-estate',
    title: 'Sonoma Valley Residence',
    category: 'Dining',
    location: 'Sonoma, California',
    year: '2024',
    area: '5,200 sq ft',
    tagline: 'Seamless indoor-outdoor entertaining framed by heritage vineyard panoramas.',
    description: 'An architectural dining pavilion centered around a 14-foot monolithic French white oak refectory table. Floor-to-ceiling pivot glass panels dissolve boundaries into the surrounding olive orchard.',
    heroImage: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80',
    ],
    materialsUsed: ['Monolithic French Oak', 'Tuscan Limestone', 'Forged Ironwork', 'Olive Green Saddle Leather'],
    palette: ['#F8F6F0', '#DFD8C9', '#8C7A5B', '#3A2A20'],
    clientVision: 'A warm wine-country hearth where family gatherings and winemaker dinners feel effortless and memorable.',
  },
  {
    id: 'copenhagen-atelier',
    title: 'Copenhagen Waterfront Study',
    category: 'Home Office',
    location: 'Christianshavn, Copenhagen',
    year: '2024',
    area: '1,900 sq ft',
    tagline: 'Nordic discipline meets rich tactile materiality and tailored library walls.',
    description: 'Custom floor-to-ceiling oiled smoked oak shelving with brass reading sconces and an expansive freeform walnut writing desk overlooking the historic canals.',
    heroImage: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1593062096033-9a26b09da705?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
    ],
    materialsUsed: ['Smoked Danish Oak', 'Bridle Leather', 'Aged Brushed Brass', 'Bouclé Wool'],
    palette: ['#EDE8DF', '#3A2A20', '#C96F37', '#1E2226'],
    clientVision: 'A scholarly, inspiring workspace for an author and international design collector.',
  },
  {
    id: 'zurich-stone-villa',
    title: 'Zurich Lake Pavilions',
    category: 'Minimal Interior',
    location: 'Lake Zurich, Switzerland',
    year: '2025',
    area: '6,400 sq ft',
    tagline: 'Monumental Valser quartzite stone meeting soft, whisper-quiet textures.',
    description: 'Strict reduction of visual noise allowing the changing light over the alpine lake to take center stage. Hand-troweled lime wash walls with integrated flush door frames and custom cashmere drapery.',
    heroImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80',
    ],
    materialsUsed: ['Valser Quartzite', 'Swiss Alpine Larch', 'Natural Lime Plaster', 'Virgin Cashmere'],
    palette: ['#F9F8F5', '#E5E1D8', '#5E5B55', '#222326'],
    clientVision: 'A serene architectural monument where exterior views and interior serenity become indistinguishable.',
  },
  {
    id: 'milan-brera-penthouse',
    title: 'Brera Duplex Penthouse',
    category: 'Luxury Apartment',
    location: 'Brera, Milan',
    year: '2025',
    area: '4,100 sq ft',
    tagline: 'Classic Milanese architectural proportions reimagined with contemporary warmth.',
    description: 'Herringbone walnut parquet floors, sculpted plaster cornices, and contemporary Italian lighting installations complement custom marble vanities and tailored velvet seating.',
    heroImage: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80',
    ],
    materialsUsed: ['Calacatta Viola Marble', 'Smoked Walnut Parquet', 'Brushed Bronze', 'Cotton Velvet'],
    palette: ['#F7F5F0', '#EDE8DF', '#E58B4D', '#2A201A'],
    clientVision: 'Celebrate Milan’s design heritage while creating an inviting, comfortable home for daily life.',
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: '1',
    author: 'Elena Vance-Mercer',
    role: 'Art Collector & Homeowner',
    location: 'Tribeca, New York',
    project: 'Cast-Iron Loft Renovation',
    quote: 'Every single detail feels intentional. The final space is not just magazine-worthy; it is extraordinarily practical, serene, and completely attuned to how our family actually moves and gathers.',
    rating: 5,
  },
  {
    id: '2',
    author: 'Marcus & Julian Thorne',
    role: 'Tech Founders & Investors',
    location: 'Sonoma Valley, CA',
    project: 'Modern Vineyard Residence',
    quote: 'CasaVera delivered a level of craft and material restraint we did not know was possible. Their team managed the entire renovation process with pristine clarity, respect for our schedule, and uncompromised taste.',
    rating: 5,
  },
  {
    id: '3',
    author: 'Dr. Sophia Lindqvist',
    role: 'Architectural Historian',
    location: 'Christianshavn, Copenhagen',
    project: 'Waterfront Study & Atelier',
    quote: 'The way they manipulate natural light, custom millwork, and warm organic textures turned our dark canal apartment into an inspiring, light-filled sanctuary. Truly exceptional professionals.',
    rating: 5,
  },
];

export const JOURNAL_POSTS = [
  {
    id: 'journal-1',
    date: 'February 2026',
    title: 'The Tactile Home: Why Texture Trumps Color in Modern Living',
    category: 'Materiality',
    readTime: '4 min read',
    excerpt: 'Exploring how unhoned stone, raw bouclé, and patinated bronze ground our senses in an increasingly digital world.',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'journal-2',
    date: 'January 2026',
    title: 'Lighting as Architecture: Crafting the Golden Hour Indoors',
    category: 'Lighting Design',
    readTime: '6 min read',
    excerpt: 'How layering low-level ambient sources and indirect warm washes changes the emotional resonance of a room after dark.',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'journal-3',
    date: 'December 2025',
    title: 'Principles of Warm Minimalism: Editing Without Coldness',
    category: 'Philosophy',
    readTime: '5 min read',
    excerpt: 'True minimalism is not sterile emptiness—it is the confident celebration of fewer, deeply meaningful objects.',
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
  },
];
